services:

  base:
    container_name: base_image
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.base
    image: base:latest

  runtime:
    container_name: runtime_image
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.runtime
    image: runtime:latest
    depends_on:
      - base

  db:
    container_name: mariadb_container
    image: mariadb:12.0.2
    env_file:
      - ../.env
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - uvlhub_network

  redis:
    container_name: redis_container
    image: "redis:8.2.1"
    restart: always
    networks:
      - uvlhub_network

  elasticsearch:
    container_name: elasticsearch_container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - uvlhub_network

  worker:
    container_name: rq_worker_container
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.worker
    image: worker:latest
    depends_on:
      - runtime
      - redis
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/app
      - ../core/:/app/core
      - ../uploads/:/app/uploads
    networks:
      - uvlhub_network

volumes:
  db_data:
  es_data:

networks:
  uvlhub_network:
    driver: bridge
    name: uvlhub_network
